Repository 42-transcendence/front-end, pull requests merged in 2023-08, with the labels that each got.

#17 [add] 2차 인증 페이지 만들기 #16
  front/app/globals.css
  front/app/main/@login/otp/page.tsx
  front/app/main/layout.tsx
  front/components/Icon/VerificationBox.tsx
Labels: feat

#40 Textfield
  front/app/auth/[src]/page.tsx
  front/app/globals.css
  front/app/main/@main/dropdown/page.tsx
  front/app/main/@main/game/page.tsx
  front/app/main/layout.tsx
  front/components/Chat/ChatDialog.tsx
  front/components/Chat/ChatHeader.tsx
  front/components/Chat/ChatMainPage.tsx
  front/components/Chat/ChatRoomBlock.tsx
  front/components/Chat/ChatSideBar.tsx
  front/components/Game/GameCharacterSelector.tsx
  front/components/Game/GameChat.tsx
  front/components/Game/GameStartButton.tsx
  front/components/NavigationBar/NavigationBar.tsx
  front/components/TextField/SearchBox.tsx
  front/components/TextField/TextField.tsx
  front/components/TextField/index.ts
  front/components/TextField/style.css
  front/package-lock.json
  front/package.json
  front/public/gamestart.svg
  front/tailwind.config.js
Labels: feat, react

#43 Chat 화면 개선
  front/app/main/@main/game/page.tsx
  front/app/main/layout.tsx
  front/components/Avatar/Avatar.tsx
  front/components/Chat/Chat.tsx
  front/components/Chat/ChatBubble.tsx
  front/components/Chat/ChatDialog.tsx
  front/components/Chat/ChatHeader.tsx
  front/components/Chat/ChatLayout.tsx
  front/components/Chat/ChatMainPage.tsx
  front/components/Chat/ChatRoomBlock.tsx
  front/components/Chat/ChatRoomMenu.tsx
  front/components/Chat/ChatSideBar.tsx
  front/components/ContextMenu/ContextMenuBase.tsx
  front/components/ContextMenu/ContextMenuItem.tsx
  front/components/ContextMenu/ContextMenu_Social.tsx
  front/components/NavigationBar/NavigationBar.tsx
  front/components/ProfileItem/ProfileItem.tsx
  front/components/TextField/SearchBox.tsx
  front/public/chat_bubble_tail.svg
  front/public/chat_bubble_tail_right.svg
  front/public/person.svg
Labels: figma, css, refactor, UI

#57 Test game page route
  front/app/main/@main/CreateGame.tsx
  front/app/main/@main/game/[[...id]]/page.tsx
  front/app/main/@main/game/page.tsx
  front/app/main/@main/page.tsx
  front/app/main/@main/social/page.tsx
Labels: feat, react

#59 크롬에서 사이드바 제대로 안나오는 이슈 진짜진짜 해결
  front/app/globals.css
  front/app/main/@main/game/page.tsx
  front/app/main/@main/layout.tsx
  front/app/page.tsx
  front/components/Avatar/Avatar.tsx
  front/components/Chat/ChatDialog.tsx
  front/components/Chat/ChatHeader.tsx
  front/components/Chat/ChatLayout.tsx
  front/components/Chat/ChatMainPage.tsx
  front/components/Chat/ChatMemberList.tsx
  front/components/Chat/ChatRoomBlock.tsx
  front/components/Chat/ChatRoomList.tsx
  front/components/Chat/ChatRoomMenu.tsx
  front/components/Chat/CreateNewRoom.tsx
  front/components/ContextMenu/ContextMenuItem.tsx
  front/components/FriendModal/FriendModal.tsx
  front/components/NavigationBar/NavigationBar.tsx
  front/components/NavigationBar/SocialButton.tsx
  front/components/ProfileItem/ProfileItem.tsx
  front/components/TextField/TextField.tsx
Labels: bug, css, UI

#71 디렉토리 구조 변경
  front/app/(main)/@home/GameButton.tsx
  front/app/(main)/@home/LogoutButton.tsx
  front/app/(main)/@home/dropdown/page.tsx
  front/app/(main)/@home/game/[[...id]]/page.tsx
  front/app/(main)/@home/page.tsx
  front/app/(main)/@home/social/page.tsx
  front/app/(main)/@home/welcome/page.tsx
  front/app/(main)/@home/welcome2/page.tsx
  front/app/(main)/@login/default.tsx
  front/app/(main)/@login/otp/page.tsx
  front/app/(main)/@login/page.tsx
  front/app/(main)/layout.tsx
  front/app/_page.tsx
  front/app/main/@login/layout.tsx
  front/app/main/@main/layout.tsx
  front/components/NavigationBar/NavigationBar.tsx
Labels: react, refactor

#80 Prettier linter config
  front/.eslintrc.json
  front/.eslintrc.yml
  front/.prettierrc.json
  front/package-lock.json
  front/package.json
  front/prettier.config.js
Labels: misc

#83 eslint 규칙을 추가했습니다.
  front/.eslintrc.json
  front/components/ImageLibrary.tsx
Labels: misc

#85 Intercept route를 이용한 채팅창 구현
  front/app/(main)/@home/(nav)/(.)chat/layout.tsx
  front/app/(main)/@home/(nav)/(.)chat/page.tsx
  front/app/(main)/@home/(nav)/GameButton.tsx
  front/app/(main)/@home/(nav)/LogoutButton.tsx
  front/app/(main)/@home/(nav)/dropdown/page.tsx
  front/app/(main)/@home/(nav)/game/[[...id]]/page.tsx
  front/app/(main)/@home/(nav)/layout.tsx
  front/app/(main)/@home/(nav)/page.tsx
  front/app/(main)/@home/(nav)/social/page.tsx
  front/app/(main)/@home/(nav)/welcome/page.tsx
  front/app/(main)/@home/(nav)/welcome2/page.tsx
  front/app/(main)/@home/chat/page.tsx
  front/app/(main)/@login/page.tsx
  front/app/(main)/layout.tsx
  front/app/globals.css
  front/components/NavigationBar/NavigationBar.tsx
  front/components/NavigationBar/SocialButton.tsx
  front/hooks/useOutSideClick.tsx
Labels: feat, react

#90 Otp field
  front/app/(main)/@login/otp/page.tsx
Labels: bug, feat, react

#88 File upload feature
  front/app/(main)/@home/(nav)/welcome/page.tsx
  front/app/(main)/@home/welcome/page.tsx
  front/app/(main)/@home/welcome2/DragDropArea.tsx
  front/app/(main)/@home/welcome2/ImageViewer.tsx
  front/app/(main)/@home/welcome2/UploadBox.tsx
  front/app/(main)/@home/welcome2/byteConversion.ts
  front/app/(main)/@home/welcome2/page.tsx
  front/components/Game/GameUserProfile.tsx
Labels: feat, react

#91 Add eslint rule
  front/.eslintrc.json
Labels: misc, priority: low
